'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppPenilaian.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2849806_copy_interface_multimedia_print_printer_107972() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2849806-copy-interface-multimedia-print-printer_107972", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4115235_exit_logout_sign_out_114030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4115235-exit-logout-sign-out_114030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4213589_calculate_calculator_doodle_education_line_school_vector_115495() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4213589-calculate-calculator-doodle-education-line-school-vector_115495", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property admin_lock_padlock_icon_205893() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin_lock_padlock_icon_205893", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property admin_user_icon_188317() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin_user_icon_188317", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property analysis_visualization_data_graph_chart_icon_262765() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("analysis_visualization_data_graph_chart_icon_262765", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_button_circular_left_arrow_symbol_icon_icons_com_74326() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back-button-circular-left-arrow-symbol_icon-icons.com_74326", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calculation_count_finance_calculator_calc_math_icon_256453() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculation_count_finance_calculator_calc_math_icon_256453", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checklist_38554() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checklist_38554", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property correct_symbol_icon_icons_com_73609() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correct-symbol_icon-icons.com_73609", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_4219() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_4219", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property effective_employees_users_team_group_icon_152042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("effective_employees_users_team_group_icon_152042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exposure_value_48_46071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exposure_value-48_46071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fileinterfacesymboloftextpapersheet_79740() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileinterfacesymboloftextpapersheet_79740", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gambar_green_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gambar green ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gambar_green_laundry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gambar green laundry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graph_analytics_charts_data_study_anaysis_icon_143871() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph_analytics_charts_data_study_anaysis_icon_143871", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property index_data_icon_161123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index_data_icon_161123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_arrow_symbol_entering_back_into_a_square_icon_icons_com_73221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login-arrow-symbol-entering-back-into-a-square_icon-icons.com_73221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout_circle_icon_206010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_circle_icon_206010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property matrix_icon_137416() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matrix_icon_137416", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu_icon_2_icon_icons_com_71856() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu_icon_2_icon-icons.com_71856", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preliminary_examination_disease_icon_145854() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preliminary_examination_disease_icon_145854", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property race_finish_ceklist_icon_208191__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("race_finish_ceklist_icon_208191 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property race_finish_ceklist_icon_208191__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("race_finish_ceklist_icon_208191 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property savetheapplication_guardar_2958() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savetheapplication_guardar_2958", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_20240101_062927_WhatsApp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot_20240101_062927_WhatsApp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_rack_telecommunications_data_server_network_devices_data_center_icon_193885() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_rack_telecommunications_data_server_network_devices_data_center_icon_19388"& _ 
                        "5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sort_by_attributes_icon_icons_com_73406() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort-by-attributes_icon-icons.com_73406", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property twocirclingarrows1_120592() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twocirclingarrows1_120592", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
